/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e3e2df',
        'on-primary-fixed': '#002201',
        secondary: '#4c6543',
        tertiary: '#003d5c',
        'on-primary-fixed-variant': '#23501e',
        error: '#ba1a1a',
        surface: '#faf9f5',
        'surface-container-low': '#f4f4f0',
        'on-background': '#1b1c1a',
        primary: '#154212',
        'on-tertiary-container': '#8cc9f9',
        'on-tertiary-fixed': '#001e30',
        'on-secondary-fixed': '#0a2006',
        'on-error': '#ffffff',
        'on-surface-variant': '#42493e',
        'surface-container-highest': '#e3e2df',
        'inverse-on-surface': '#f2f1ed',
        'outline-variant': '#c2c9bb',
        'secondary-container': '#ceebc0',
        background: '#faf9f5',
        'tertiary-fixed': '#cae6ff',
        'surface-dim': '#dbdad6',
        'surface-tint': '#3b6934',
        'primary-fixed-dim': '#a1d494',
        'tertiary-fixed-dim': '#90cdfd',
        'on-secondary-container': '#526b49',
        'surface-bright': '#faf9f5',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#2f312e',
        'on-secondary-fixed-variant': '#354d2d',
        'surface-container': '#efeeea',
        'on-primary-container': '#9dd090',
        'primary-container': '#2d5a27',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e9e8e4',
        'error-container': '#ffdad6',
        'secondary-fixed': '#ceebc0',
        'on-surface': '#1b1c1a',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#b3cfa5',
        'inverse-primary': '#a1d494',
        'primary-fixed': '#bcf0ae',
        'on-tertiary-fixed-variant': '#004b70',
        'tertiary-container': '#00557e',
        outline: '#72796e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        'margin-mobile': '16px',
        lg: '48px',
        'margin-desktop': '32px',
        base: '8px',
        gutter: '24px',
        md: '24px',
        xl: '80px',
        xs: '4px',
        // Fixed app-bar height. Named so the value stays in one place instead
        // of being derived from logo size plus padding at each call site.
        header: '80px',
        // Minimum comfortable touch target (WCAG 2.5.5). Do not go below 44px:
        // this drives the bell/logout/account hit areas, not the icon glyph,
        // which stays 24px on its own.
        touch: '44px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
